---
title: "Angela Andreella"
output: 
  html_document:
    toc: FALSE
---

**Assistant professor in social statistics [RTD-A, SSD: SECS-S/05 (Statistica sociale)] @ University of Venice**


#### `r emoji::emoji("bulb")` Research interest

Mainly, my interest is to connect the statistic with different fields, such as social sciences, health sciences, psychology, neuroscience, and medicine improving both areas. My challenging is then analyzing these datas and their related problems with proper and/or novel statistical approaches. For that, I am a member of the [Psicostat](http://ip146179.psy.unipd.it/psicostat/web/) group at the University of Padova, and of the [LoLa](https://lola.projects.unibz.it/?page_id=367&lang=it) group.

My statistical interests are in methods that permits to understand and manage high-dimensional data, i.e., dimension reduction techinques, statistical shape analysis, permutation tests, multiple testing and selective inference.


#### `r emoji::emoji("bird")` Something about me

I am currently an assistant professor in social statistic at the Department of Economics of the University Ca’ Foscari Venezia. I am working on various projects mainly in the social statistic field, where novel statistical approaches are used to to redefine the design of services to citizens and communities to customize and adapt interventions to the characteristics of the territories and communities of reference.

Previously, I did a Post-Doc at the Department of Statistical Sciences of the University of Padova under the supervision of Professor Bruno Scarpa and Livio Finos. Here, we worked on sample size estimation in the power analysis context for PLS classification.

I also did a Post-Doc at the Department of Science and Technology of the University of Insubria with the supervision of Professor Antonietta Mira. The project was focused on modeling the data from emergency call centers across the Lombardy region in Italy.

I finished my Ph.D. in Statistical Sciences under the supervision of Professor Livio Finos about statistical methods to analyze neuroscience data, e.g., fMRI data.

One Ph.D. thesis project was about a spatial regularization of the Procrustes-based method used in the functional alignment of brain data, i.e., the ProMises (Procrustes von Mises-Fisher) model. I am collaborating with Professor James Haxby from the Department of Psychological and Brain Sciences at Dartmouth College and with the Haxby Lab.

Another project of the Ph.D. thesis was about a permutation-based approach of the All Resolution Inference method under the supervision of Professor Jelle Goeman from the Department of Biomedical Data Sciences and Professor Wouter Weeda from the Department of Psychology at Leiden University. The method fixes the spatial specificity paradox, computing lower bounds for each cluster’s number of active voxels. The method can be applied as many times as the user want, still controlling the family-wise error rate.

I am also collaborating with Paolo Brambilla and Giuseppe Delvecchio from Polyclinic of Milan on various psychiatrical and psychological projects.



