---
title: ""
output: 
  html_document:
    toc: FALSE
---

### `r emoji::emoji("book")` Articles in refereed journals

* **Andreella, A.**, Monasta, L., and Campostrini, S. 2023. A novel definition of Italian comorbidity based on diseases detected by the surveillance system PASSI and the Global Burden of Diseases disability weights. Population Health Metrics, DOI: 10.1186/s12963-023-00317-7

* **Andreella, A.**, Mira, A., Balafas, S., Wit, E. C., Ruggeri, F., Nattino, G., Ghilardi, G., and Bertolini, G. 2023. A predictive model for planning emergency events rescue during COVID-19 in Lombardy, Italy. Statistical Methods & Applications, DOI: 10.1007/s10260-023-00725-x

* **Andreella, A.**, Finos, L., Weeda, W., Hemerik, J., and Goeman, J. 2022. Permutation-based true discovery proportions for fMRI cluster analysis. Statistics in Medicine, DOI: 10.1002/sim.9725 [LINK](https://onlinelibrary.wiley.com/doi/full/10.1002/sim.9725)

* **Andreella, A.**, De Santis, R., Vesely, A. and Finos, L. 2022. Procrustes-based distances for exploring between-matrices similarity, Statistical Methods & Applications, DOI: 0.1007/s10260-023-00689-y [LINK](https://link.springer.com/article/10.1007/s10260-023-00689-y)

* **Andreella, A.**, Finos, L., and Lindquist, M. 2022. Enhanced hyperalignment via spatial prior information. Human Brain Mapping [Link](https://onlinelibrary.wiley.com/doi/full/10.1002/hbm.26170)

* **Andreella, A.**, and Livio Finos. 2022. Procrustes analysis for high dimensional data. Psychometrika. [Link](https://link.springer.com/article/10.1007/s11336-022-09859-5)

* Pigoni, A., Delvecchio, G., Dusi, N., Schiena, G., **Andreella, A.**, Finos, L., Cecchetto, F., Perlini, C., Rossetti, M. G., Ferro, A., Bellani, M., Lasalvia, A., Ruggeri, M., and Brambilla, P. 2022. Insula volumes in first-episode and chronic psychosis: A longitudinal MRI study. Schizophrenia Research [Link](https://www.sciencedirect.com/science/article/abs/pii/S0920996421005326?via%3Dihub)


* Zandonella Callegher, C., Bertoldo, G., Toffalini, E., Vesely, **A., Andreella**, A., Pastore, M., e Altoe, G. 2021. PRDA: An R package for Prospective and Retrospective Design Analysis. Journal of Open Source Software, 6(58), 2810, ISSN: 2475-9066 [Link](https://joss.theoj.org/papers/10.21105/joss.02810.pdf)

* Ciappolino, V., DelVecchio, G., Prunas, C., **Andreella, A.**, Finos, L., Caletti, E., Siri, F., Mazzocchi, A., Botturi, A., Turolo, S., Agostoni, C. e Brambilla, P. 2020. The Effect of DHA Supplementation on Cognition in Patients with Bipolar Disorder: An Exploratory Randomized Control Trial. Nutrients [Link](https://www.mdpi.com/2072-6643/12/3/708)

* Delvecchio, G., Caletti, E., Perlini, C., Siri, F. M., **Andreella, A.**, Finos, F., Bellani, M., Fabbro, F., Lasalvia, A., Bonetto, C., Cristofalo, D., Scocco, P., D'Agostino, A., Torresani, S., Imbesi, M., bellini, F., Veronese, A., Bressi, V., e Brambilla, P. 2019. Altered syntactic abilities in first-episode patients: An inner phenomenon characterizing psychosis. European Psychiatry [Link](https://www.cambridge.org/core/journals/european-psychiatry/article/altered-syntactic-abilities-in-first-episode-patients-an-inner-phenomenon-characterizing-psychosis/B649A5C97CF59E0E0385C5CAF690A9D5)


* Caletti, E., Delvecchio, G., **Andreella, A.**, Finos, L., Perlini, C., Tavano, A., Lasalvia, A., Bonetto, C., Cristofalo, D., Lamonaca,
D., Ceccato, C., Pileggi, F., FaustoMazzi, F., Santonastaso, P., Ruggeri, M., Bellani, M., and Brambilla, P. 2018. Prosody abilities in a large sample of affective and nonaffective first episode psychosis patients. Comprehensive Psychiatry doi: 10.1016/j.comppsych.2018.07.004, 86, 31-38 [Link](https://www.sciencedirect.com/science/article/pii/S0010440X18301135?casa_token=HpdVtMnO85MAAAAA:hmoaCpCM0JO6zN-JqHhuemu63m7Lp8l1BxQR1R0hy2A_7B6__aWrOrwUazdPbw9ogSpIOA4fBuo)


### `r emoji::emoji("book")` Refereed conference proceedings

* **Andreella, A.**, Campostrini, S. 2023. Suitable statistical approaches for novel policies: spatial clusters of childcare’s services in Veneto, Italy. Proceedings of the 5th International Conference on Advanced Research Methods and Analytics (CARMA 2023), 205--212, ISBN: 9788413960869 

* **Andreella, A.**, Monasta, L., Campostrini, S. 2023. A novel definition of comorbidity based on the Global Burden of Diseases project weights. Book of the Short Papers SIS 2023, 566--571, ISBN 9788891935618

* Vesely, A., and **Andreella, A.**. 2023. How active is a genetic pathway? Comparative analysis of post-hoc permutation-based methods. Book of the Short Papers SIS 2023, 1268--1273, ISBN 9788891935618

*  **Andreella, A.**, De Santis, R. and Finos, L. 2022. Valid inference for group analysis of functionally aligned fMRI images. Book of Short Papers SIS 2022, 1987--1992, ISBN: 9788891932310

* Vesely, A.,  **Andreella, A.**, Goeman, J., Finos, L. 2022. Resampling-Based Inference for High-Dimensional Regression. Book of Short Papers SIS 2022, 1327--1332, ISBN: 9788891932310

* Vesely, A., Finos, L., Goeman, J. J., and  **Andreella, A.** 2021. Valid Double-Dipping via Permutation-Based Closed Testing. Book of Short Papers SIS 2021, ISBN: 9788891927361

*  **Andreella, A.** and Finos, L. 2021. Functional alignment by the light approach of the von Mises-Fisher-Procrustes model. Book of Short Papers SIS 2021, ISBN: 9788891927361

* **Andreella, A.** and Finos, L. 2020. A Statistical Approach to the Alignment of fMRI Data. Book of Short Papers SIS 2020, ISBN: 9788891910776


### `r emoji::emoji("book")` Submitted and working papers

* **Andreella, A.**, Vesely, A., Wouter, W., and Goeman, J. 2023. Selective inference for fMRI cluster-wise analysis, issues, and recommendations for template selection: A comment on Blain et al [submitted](https://arxiv.org/abs/2307.02115)

* **Andreella, A.**, Aliverti, E., Caldura, F., and Campostrini, S. 2023. Spatial clusters for demand and supply of childcare services in Italy [submitted](https://arxiv.org/abs/2401.07600)

* **Andreella, A.**, Finos, L., Scarpa, B., and Stocchero, M. 2023. Toward a power analysis and sample size estimation for
PLS-based methods [submitted](https://arxiv.org/abs/2403.10289)

* **Andreella, A.**, Hemerik, J, Goeman, J., Finos, L., Robust Inference for Multivariate Generalized Linear Mixed Models: An Approach Based on Score Sign Flipping [submitted](https://arxiv.org/abs/2401.17993)

* **Andreella, A.**, Campostrini, S., Caldura, F., Bertarelli, G. 2023. A two-step model to analyze the inclusivity’s distribution of Italian childcare services [working paper]

* **Andreella, A.**, Campostrini, S. 2024. Analyzing Compression of Comorbidity in Italy: A Mixture Model with Regional Random Effects [working paper]

* Xu, N., Solari, A., Vesely, A., **Andreella, A.**, Goeman, J. 2024. Shortcuts for permutation-based closed testing [working paper]

* **Andreella, A.**, Campostrini, S. 2024. Work Realities and Behavioral Risk Factors in Italy [working paper]
